spring:
  datasource:
    url: jdbc:h2:mem:pay_together
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  data:
    redis:
      host: localhost
      password:
      port: 6379

  session:
    redis:
      namespace: session-pay